### ISSUE TITLE
[EPIC] Add support for all array expressions

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#1042]
### What is the problem the feature request solves?

We would like to support all array operations natively in Comet.

- [ ] array: SELECT array(1, 2, 3)
- [ ] array_agg: SELECT array_agg(col) FROM VALUES (1), (2), (1) AS tab(col)
- [ ] array_append: SELECT array_append(array('b', 'd', 'c', 'a'), 'd')
- [ ] array_compact: SELECT array_compact(array(1, 2, 3, null))
- [ ] array_contains: SELECT array_contains(array(1, 2, 3), 2)
- [ ] array_distinct: SELECT array_distinct(array(1, 2, 3, null, 3))
- [ ] array_except: SELECT array_except(array(1, 2, 3), array(1, 3, 5))
- [ ] array_insert: SELECT array_insert(array(1, 2, 3, 4), 5, 5)
- [ ] array_intersect: SELECT array_intersect(array(1, 2, 3), array(1, 3, 5))
- [ ] array_join: SELECT array_join(array('hello', 'world'), ' ')
- [ ] array_max: SELECT array_max(array(1, 20, null, 3))
- [ ] array_min: SELECT array_min(array(1, 20, null, 3))
- [ ] array_position: SELECT array_position(array(3, 2, 1), 1)
- [ ] array_remove: SELECT array_remove(array(1, 2, 3, null, 3), 3)
- [ ] array_repeat: SELECT array_repeat('123', 2)
- [ ] array_size: SELECT array_size(array('b', 'd', 'c', 'a'))
- [ ] array_sort: SELECT array_sort(array(5, 6, 1), (left, right) -> case when left < right then -1 when left > right then 1 else 0 end)
- [ ] array_union: SELECT array_union(array(1, 2, 3), array(1, 3, 5))
- [ ] arrays_overlap: SELECT arrays_overlap(array(1, 2, 3), array(3, 4, 5))
- [ ] arrays_zip: SELECT arrays_zip(array(1, 2, 3), array(2, 3, 4))

**Comment by SemyonSinchenko** [comment]
I would like to work on `array_zip`

**Comment by dharanad** [comment]
I would like to work on `array_contains ` followed up by `array_min` & `array_max`

**Comment by jatin510** [comment]
@andygrove 

```
 select array(1, 2, 3) ;
24/12/19 00:13:47 WARN CometSparkSessionExtensions$CometExecRule: Comet cannot execute some parts of this plan natively (set spark.comet.explainFallback.enabled=false to disable this logging):
 Project [COMET: Project is not native because the following children are not native (Scan OneRowRelation)]
+-  Scan OneRowRelation [COMET: Scan OneRowRelation is not supported]

[1,2,3]
```

is `array` function not supported in comet yet ?
it is marked as done above ?

**Comment by dharanad** [comment]
> @andygrove
> 
> ```
>  select array(1, 2, 3) ;
> 24/12/19 00:13:47 WARN CometSparkSessionExtensions$CometExecRule: Comet cannot execute some parts of this plan natively (set spark.comet.explainFallback.enabled=false to disable this logging):
>  Project [COMET: Project is not native because the following children are not native (Scan OneRowRelation)]
> +-  Scan OneRowRelation [COMET: Scan OneRowRelation is not supported]
> 
> [1,2,3]
> ```
> 
> is `array` function not supported in comet yet ? it is marked as done above ?

If you can observe the error logs.  `Scan OneRowRelation` is not supported by Comet yet. Which is why vanilla Project operator is used instead of CometProject

**Comment by dharanad** [comment]
Many array functions in DataFusion currently have limited visibility. I have a pull request that addresses this issue https://github.com/apache/datafusion/pull/14030
We can support for a wider range of array functions when comet is updated it consume next DataFusion release.

**Comment by kazantsev-maksim** [comment]
I would like to work on array_except followed up by array_compact. 
@andygrove

**Comment by andygrove** [comment]
All listed array expressions are now implemented in `spark/src/main/scala/org/apache/comet/serde/arrays.scala`. The remaining `array_agg` (CollectList) work is tracked separately in #2524, so this EPIC can be closed.
