### ISSUE TITLE
[EPIC] Complex Type Support

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#1043]
### What is the problem the feature request solves?

We would like Comet to fully support complex types (arrays, structs, and maps). This issue is for tracking all of the individual issues.

Google doc: https://docs.google.com/document/d/1eiDFEScPjxBMahJW6lmBI8JjVlI6CwhiJgkTSsTvPVY/edit?usp=sharing

### Implement new native scans based on DataFusion's DataSourceExec

We now have new `native_datafusion` and `native_iceberg_compat` scans that use DataFusion's `DataSourceExec`, which already supports complex types. 

We need to fix the remaining Spark SQL test failures:

- https://github.com/apache/datafusion-comet/issues/1542
- https://github.com/apache/datafusion-comet/issues/1545

Known issues:

- https://github.com/apache/datafusion-comet/issues/1348
- https://github.com/apache/datafusion-comet/issues/1754
- https://github.com/apache/datafusion-comet/issues/1758
- https://github.com/apache/datafusion-comet/issues/1750
- https://github.com/apache/datafusion-comet/issues/1574
- https://github.com/apache/datafusion-comet/issues/1488

### Other scan-related work

These items may not be relevant to all users, but for some environments, there is more work required to allow the new `ParquetExec` scans to be used. Comet's current default `native_comet` scan is JVM-based and leverages Hadoop data source functionality that is not available in DataFusion.

- https://github.com/apache/datafusion-comet/issues/1766
- Wrap Hadoop file readers in JNI so that we can call from Rust, to support use cases such as encryption
- https://github.com/apache/datafusion-comet/issues/1082
- Custom Authentication for cloud storage
- [HDFS Support](https://github.com/apache/datafusion-comet/issues/1336)

### Supporting expressions that operate on complex types

- Expressions
  - [ ] Array
    - [ ] https://github.com/apache/datafusion-comet/issues/1042
    - [ ] Update to_json to support arrays
    - [ ] Implement CAST from array to string
  - [ ] Struct
    - [x] https://github.com/apache/datafusion-comet/issues/815
    - [x] https://github.com/apache/datafusion-comet/issues/814
    - [ ] https://github.com/apache/datafusion-comet/issues/813
  - [ ] Map
    - [ ] https://github.com/apache/datafusion-comet/issues/1044
    - [ ] Implement CAST from Map to String
    - [ ] Add map support to `to_json`

### Performance

- Create benchmarks for complex types

### Testing

- https://github.com/apache/datafusion-comet/issues/1486
- https://github.com/apache/datafusion-comet/issues/1489
- Fuzz testing

Older / related issues:

- https://github.com/apache/datafusion-comet/issues/1040
- https://github.com/apache/datafusion-comet/issues/434

**Comment by andygrove** [comment]
I think we can close this epic now and start filing issues for any remaining bugs and missing features
