### ISSUE TITLE
[EPIC] Add support for all Map functions

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#1044]
### What is the problem the feature request solves?

- [ ] [[ ] operator](https://docs.databricks.com/en/sql/language-manual/functions/bracketsign.html)
- [ ] [map_concat function](https://docs.databricks.com/en/sql/language-manual/functions/map_concat.html)
- [ ] [map_entries function](https://docs.databricks.com/en/sql/language-manual/functions/map_entries.html)
- [ ] [map_filter function](https://docs.databricks.com/en/sql/language-manual/functions/map_filter.html)
- [ ] [map_from_arrays function](https://docs.databricks.com/en/sql/language-manual/functions/map_from_arrays.html)
- [ ] [map_from_entries function](https://docs.databricks.com/en/sql/language-manual/functions/map_from_entries.html)
- [ ] [map_keys function](https://docs.databricks.com/en/sql/language-manual/functions/map_keys.html)
- [ ] [map_values function](https://docs.databricks.com/en/sql/language-manual/functions/map_values.html)
- [ ] [map_zip_with function](https://docs.databricks.com/en/sql/language-manual/functions/map_zip_with.html)

**Comment by kazantsev-maksim** [comment]
I would like work on `map_filter function`

**Comment by kurosch** [comment]
I would like to work on the `[]` operator. I assume it has to be implemented for arrays and maps.
