### ISSUE TITLE
[EPIC] Spark-compatible cast / try_cast operations

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#286]
### What is the problem the feature request solves?

Comet currently delegates to DataFusion for many cast operations, and the behavior is not guaranteed to match Spark. This epic is to track fully implementing Spark-compatible `cast` and `try_cast` operations in Comet, with support for ANSI mode.

For each item in this list to be considered complete, we should have scala tests demonstrating that `cast` and `try_cast` produce the same results as Spark, both with ANSI mode enabled and disabled, using fuzz testing to find edge cases. We can update this list with links to issues as we make progress.

For cast operations that we cannot easily support with full compatibility, we should either fall back to Spark or provide a configuration that the user can enable to allow the operation to run in Comet. We should also provide documentation explaining any differences in behavior compared to Spark.

- [x] Cast from string to another type
  - [x] Boolean - https://github.com/apache/datafusion-comet/pull/290
  - [x] Integral Types (byte, short, int, long) - https://github.com/apache/datafusion-comet/pull/307
  - [x] Floating-point (float, double) - https://github.com/apache/datafusion-comet/issues/326
  - [x] Decimal - https://github.com/apache/datafusion-comet/issues/325
  - [x] Date - https://github.com/apache/datafusion-comet/issues/327
  - [x] Timestamp - https://github.com/apache/datafusion-comet/issues/328 and https://github.com/apache/datafusion-comet/issues/376
- [x] Cast to string from primitive types
  - [x] Boolean -  https://github.com/apache/datafusion-comet/pull/351
  - [x] Integral Types (byte, short, int, long) - https://github.com/apache/datafusion-comet/pull/351
  - [x] Floating-point (float, double) - https://github.com/apache/datafusion-comet/issues/312
  - [x] Decimal - seems to correct but needs tests to confirm, also should fall back to Spark if `spark.sql.legacy.allowNegativeScaleOfDecimal` is true and scale is negative - https://github.com/apache/datafusion-comet/pull/3939
  - [x] Date - seems correct but needs tests to confirm
  - [x] Timestamp - seems correct but needs tests to confirm
- [x] Cast between numeric types
  - [x] Integral to Integral - https://github.com/apache/datafusion-comet/issues/311
  - [x] Integral to Boolean - https://github.com/apache/datafusion-comet/pull/351
  - [x] Integral to Decimal - https://github.com/apache/datafusion-comet/issues/2049
  - [x] Integral to Floating-point - https://github.com/apache/datafusion-comet/pull/351
  - [x] Floating-point to Boolean - https://github.com/apache/datafusion-comet/pull/351
  - [x] Floating-point to Decimal - https://github.com/apache/datafusion-comet/issues/371
  - [x] Floating-point to Integral - https://github.com/apache/datafusion-comet/issues/350
  - [x] Decimal to Boolean - fails because arrow does not support this cast - https://github.com/apache/datafusion-comet/pull/3948
  - [x] Decimal to Integral - same issues as https://github.com/apache/datafusion-comet/issues/350
  - [x] Decimal to Floating-point - seems correct but needs tests to confirm - https://github.com/apache/datafusion-comet/pull/3948
  - [x] https://github.com/apache/datafusion-comet/issues/375
- [x]  Cast between temporal types
  - [x] Date to boolean/int/float/decimal - results are incorrect
  - [x] Date to Timestamp / TimestampNTZ
  - [x] Timestamp to boolean/int/float/decimal - https://github.com/apache/datafusion-comet/issues/352
  - [x] Timestamp to Date 
- [x] Other
  - [x] https://github.com/apache/datafusion-comet/issues/377
  - [x] https://github.com/apache/datafusion-comet/issues/378

In addition to the above tasks, we also need to do the following:

- [x] Implement a mechanism where we can selectively fall back to Spark for specific cast operations (https://github.com/apache/datafusion-comet/pull/337 )
- [x] Write documentation that explains any differences between Comet and Spark
- [x] https://github.com/apache/datafusion-comet/issues/374

**Comment by edmondop** [comment]
@andygrove do we have already a framework for fuzz testing in Scala (i.e. ScalaCheck?) Should anyone wait until you are done with the first ones so you establish a pattern?

**Comment by andygrove** [comment]
> @andygrove do we have already a framework for fuzz testing in Scala (i.e. ScalaCheck?) Should anyone wait until you are done with the first ones so you establish a pattern?

There is a `CometCastSuite` and I am working on a PR right now to improve this and I am also implementing cast string to boolean (an easy one) so that there is an example for others to learn from. I should have a draft PR up on Monday.

**Comment by andygrove** [comment]
I am now working on cast string -> integral types. I will have a PR up later this week.

**Comment by edmondop** [comment]
@andygrove can I take care of this " Implement a mechanism where we can selectively fall back to Spark for specific cast operations" ? I was looking at the top of the list, but everything was quickly taken

**Comment by andygrove** [comment]
@edmondop feel free to pick up other items on the list that don't have issues yet (I will start filing more!)

I added an example of falling back top Spark for cast string to timestamp in https://github.com/apache/datafusion-comet/pull/337 so we do have an approach. I will update that item in this epic.

**Comment by coderfender** [comment]
> ### What is the problem the feature request solves?
> Comet currently delegates to DataFusion for many cast operations, and the behavior is not guaranteed to match Spark. This epic is to track fully implementing Spark-compatible `cast` and `try_cast` operations in Comet, with support for ANSI mode.
> 
> For each item in this list to be considered complete, we should have scala tests demonstrating that `cast` and `try_cast` produce the same results as Spark, both with ANSI mode enabled and disabled, using fuzz testing to find edge cases. We can update this list with links to issues as we make progress.
> 
> For cast operations that we cannot easily support with full compatibility, we should either fall back to Spark or provide a configuration that the user can enable to allow the operation to run in Comet. We should also provide documentation explaining any differences in behavior compared to Spark.
> 
> * * [ ]  Cast from string to another type
>     
>     * [x]  Boolean - [feat: Support ANSI mode in CAST from String to Bool #290](https://github.com/apache/datafusion-comet/pull/290)* [x]  Integral Types (byte, short, int, long) - [feat: Implement Spark-compatible CAST from string to integral types #307](https://github.com/apache/datafusion-comet/pull/307)* [ ]  Floating-point (float, double) - [Implement Spark-compatible CAST from String to Floating Point #326](https://github.com/apache/datafusion-comet/issues/326)* [ ]  Decimal - [Implement Spark-compatible CAST from String to Decimal #325](https://github.com/apache/datafusion-comet/issues/325)* [x]  Date - [Implement Spark-compatible CAST from String to Date #327](https://github.com/apache/datafusion-comet/issues/327)* [ ]  Timestamp - [Implement Spark-compatible CAST from String to Timestamp #328](https://github.com/apache/datafusion-comet/issues/328) and [Cast string to timestamp remaining work #376](https://github.com/apache/datafusion-comet/issues/376)* [ ]  Cast to string from primitive types
>     
>     * [x]  Boolean -  [chore: Add more cast tests and improve test framework #351](https://github.com/apache/datafusion-comet/pull/351)* [x]  Integral Types (byte, short, int, long) - [chore: Add more cast tests and improve test framework #351](https://github.com/apache/datafusion-comet/pull/351)* [x]  Floating-point (float, double) - [Implement Spark-compatible CAST float/double to string #312](https://github.com/apache/datafusion-comet/issues/312)* [ ]  Decimal - seems to correct but needs tests to confirm, also should fall back to Spark if `spark.sql.legacy.allowNegativeScaleOfDecimal` is true and scale is negative* [ ]  Date - seems correct but needs tests to confirm* [ ]  Timestamp - seems correct but needs tests to confirm* [ ]  Cast between numeric types
>     
>     * [x]  Integral to Integral - [Implement Spark-compatible CAST between integer types #311](https://github.com/apache/datafusion-comet/issues/311)* [x]  Integral to Boolean - [chore: Add more cast tests and improve test framework #351](https://github.com/apache/datafusion-comet/pull/351)* [ ]  Integral to Decimal - [Implement Spark-compatible cast from integral types to decimal #2049](https://github.com/apache/datafusion-comet/issues/2049)* [x]  Integral to Floating-point - [chore: Add more cast tests and improve test framework #351](https://github.com/apache/datafusion-comet/pull/351)* [x]  Floating-point to Boolean - [chore: Add more cast tests and improve test framework #351](https://github.com/apache/datafusion-comet/pull/351)* [x]  Floating-point to Decimal - [Implement Spark-compatible CAST from floating-point to decimal #371](https://github.com/apache/datafusion-comet/issues/371)* [x]  Floating-point to Integral - [Implement Spark-compatible CAST from float/double to integer types #350](https://github.com/apache/datafusion-comet/issues/350)* [ ]  Decimal to Boolean - fails because arrow does not support this cast* [x]  Decimal to Integral - same issues as [Implement Spark-compatible CAST from float/double to integer types #350](https://github.com/apache/datafusion-comet/issues/350)* [ ]  Decimal to Floating-point - seems correct but needs tests to confirm* [x]  [Implement Spark-compatible cast between decimals with different precision and scale #375](https://github.com/apache/datafusion-comet/issues/375)* [ ]   Cast between temporal types
>     
>     * [ ]  Date to boolean/int/float/decimal - results are incorrect* [ ]  Date to Timestamp / TimestampNTZ* [ ]  Timestamp to boolean/int/float/decimal - [Implement Spark-compatible CAST from timestamp to numeric types #352](https://github.com/apache/datafusion-comet/issues/352)* [ ]  Timestamp to Date* [ ]  Other
>     
>     * [x]  [Implement Spark-compatible cast to/from binary type #377](https://github.com/apache/datafusion-comet/issues/377)* [ ]  [Implement Spark-compatible CAST to/from TimestampNTZType #378](https://github.com/apache/datafusion-comet/issues/378)
> 
> In addition to the above tasks, we also need to do the following:
> 
> * [x]  Implement a mechanism where we can selectively fall back to Spark for specific cast operations ([feat: Disable cast string to timestamp by default #337](https://github.com/apache/datafusion-comet/pull/337) )[ ]  Write documentation that explains any differences between Comet and Spark[x]  [Add support for TryCast expression in Spark 3.2 and 3.3 #374](https://github.com/apache/datafusion-comet/issues/374)

Raised issue : https://github.com/apache/datafusion-comet/issues/2489 to track Decimal to Boolean cast op and integer to decimal cast op #2472

**Comment by coderfender** [comment]
Raised : https://github.com/apache/datafusion-comet/pull/2490 for Decimal -> Boolean cast native support

**Comment by coderfender** [comment]
Raised : https://github.com/apache/datafusion-comet/pull/2835 for full String -> float/Double casts

**Comment by coderfender** [comment]
Raised #2926 to track String -> Decimal Type casting

**Comment by andygrove** [comment]
@coderfender do you think we can close this epic now? Do you we need to create any additional issues for remaining work?

**Comment by coderfender** [comment]
@andygrove I believe we can close / update this EPIC given that most of the expressions are supported and we also now have documentation with cast support at different eval modes. We might however want to create new epic for temporal casts which @parthchandra might be working on

**Comment by attilapiros** [comment]
For your awareness, this Spark PR was recently submitted: https://github.com/apache/spark/pull/53458 
and this will affect how an invalid UTF-8 from binary to string will be casted.

**Comment by coderfender** [comment]
Issue to to cast from date to timestamp : https://github.com/apache/datafusion-comet/issues/3400 
PR : https://github.com/apache/datafusion-comet/pull/3383

**Comment by boudica-dev-eng** [comment]
I haven't found an issue for Long -> Timestamp. Is this planned?

**Comment by coderfender** [comment]
whole numbers to binary and bool to decimal : https://github.com/apache/datafusion-comet/pull/3083

**Comment by coderfender** [comment]
numeric (non int) to timestamp : https://github.com/apache/datafusion-comet/issues/3560

**Comment by andygrove** [comment]
All items in this epic are now completed 🎉 so let's close this and just file individual issues for any are casts that need implementing.

**Comment by coderfender** [comment]
This is great news @andygrove !
