### ISSUE TITLE
[EPIC] Performance focus for 0.2.0 Release

### ISSUE THREAD

**Issue by andygrove** [apache/datafusion-comet#717]
### What is the problem the feature request solves?

I am creating this epic to track performance issues that the community is working on for the 0.2.0 release.

- [x] https://github.com/apache/datafusion-comet/issues/679
- [x] https://github.com/apache/datafusion-comet/issues/670
- [x] Evaluate performance improvement from fusing aggregate and filter to use avoid copying the batch (see https://github.com/apache/datafusion/issues/5944#issuecomment-2260794953)
- [ ] https://github.com/apache/datafusion-comet/issues/745
- [ ] https://github.com/apache/datafusion-comet/issues/808
